// This file is auto-generated by ./bin/rails stimulus:manifest:update
// Run that command whenever you add a new controller or create them with
// ./bin/rails generate stimulus controllerName

import { application } from "./application"

import AnnotateController from "./annotate_controller"
application.register("annotate", AnnotateController)

import FlatpickrController from "./flatpickr_controller"
application.register("flatpickr", FlatpickrController)

import HelloController from "./hello_controller"
application.register("hello", HelloController)

import LoadingController from "./loading_controller"
application.register("loading", LoadingController)

import ReadMoreController from "./read_more_controller"
application.register("read-more", ReadMoreController)

import CarouselController from "./carousel_controller"
application.register("carousel", CarouselController)
